# Generated by Django 3.2.4 on 2023-09-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.AutoField(db_column='Id_Categoria', primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('Id_Pais', models.AutoField(db_column='Id_Pais', primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(db_column='Descripcion')),
                ('Codigo_Idioma', models.TextField(db_column='Codigo_Idioma')),
            ],
            options={
                'db_table': 'Paises',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
