# Generated by Django 3.2.4 on 2023-12-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellido_P',
            new_name='Apellido_Pa',
        ),
    ]
