# Generated by Django 3.2.4 on 2023-12-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_apellido_p_usuario_apellido_pa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Idioma',
        ),
        migrations.RemoveField(
            model_name='libro_has_autor',
            name='Fk_Id_Autor',
        ),
        migrations.RemoveField(
            model_name='libro_has_autor',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='libro_has_genero',
            name='Fk_Id_Genero',
        ),
        migrations.RemoveField(
            model_name='libro_has_genero',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='libro_has_idioma',
            name='Fk_Id_Idioma',
        ),
        migrations.RemoveField(
            model_name='libro_has_idioma',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='Fk_Id_Usuario',
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Libro_has_Autor',
        ),
        migrations.DeleteModel(
            name='Libro_has_Genero',
        ),
        migrations.DeleteModel(
            name='Libro_has_Idioma',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
