# Generated by Django 3.2.4 on 2023-12-07 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231206_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id_Libro', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Registro', models.DateField()),
                ('Titulo', models.TextField()),
                ('Sinopsis', models.CharField(max_length=300)),
                ('en_biblioteca', models.BooleanField(default=True)),
                ('Fk_Id_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editorial')),
                ('Fk_Id_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('Id_Resena', models.AutoField(primary_key=True, serialize=False)),
                ('Calificacion', models.IntegerField()),
                ('Comentario', models.CharField(max_length=150)),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Idioma',
            fields=[
                ('Id_Libro_has_Idioma', models.AutoField(primary_key=True, serialize=False)),
                ('Fk_Id_Idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Idioma',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Genero',
            fields=[
                ('Id_Libro_has_Genero', models.AutoField(primary_key=True, serialize=False)),
                ('Fk_Id_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Genero',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Autor',
            fields=[
                ('Id_Libro_has_Autor', models.AutoField(primary_key=True, serialize=False)),
                ('Fk_Id_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Autor',
            },
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('Id_Biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Biblioteca',
            },
        ),
    ]
