# Generated by Django 3.2.4 on 2023-09-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('Id_Idioma', models.AutoField(db_column='Id_Idioma', primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(db_column='Descripcion')),
                ('Codigo_Idioma', models.TextField(db_column='Codigo_Idioma')),
            ],
            options={
                'db_table': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('Id_Pais', models.AutoField(db_column='Id_Pais', primary_key=True, serialize=False)),
                ('Descripcion', models.TextField(db_column='Descripcion')),
                ('Codigo_Pais', models.TextField(db_column='Codigo_Pais')),
            ],
            options={
                'db_table': 'Paises',
            },
        ),
    ]
