# Generated by Django 3.2.4 on 2023-09-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_idioma_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('Id_Editorial', models.AutoField(db_column='Id_Editorial', primary_key=True, serialize=False)),
                ('Nombre_Editorial', models.TextField(db_column='Nombre_Editorial')),
                ('Sitio_Web', models.URLField(db_column='Sitio_Web')),
                ('fk_pais', models.ForeignKey(db_column='fk_pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
            ],
            options={
                'db_table': 'Editoriales',
            },
        ),
    ]
