# Generated by Django 3.2.4 on 2023-09-19 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_editorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Id_Autor', models.AutoField(db_column='Id_Autor', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=25)),
                ('Apellido_P', models.CharField(db_column='Apellido_P', max_length=20)),
                ('Apellido_M', models.CharField(db_column='Apellido_M', max_length=20)),
                ('Biografia', models.CharField(db_column='Biografia', max_length=200)),
                ('Fk_pais', models.ForeignKey(db_column='fk_pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
            ],
            options={
                'db_table': 'Autores',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
