# Generated by Django 3.2.4 on 2023-09-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.IntegerField(db_column='Telefono'),
        ),
    ]
