# Generated by Django 3.2.4 on 2024-01-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_biblioteca_libro_has_autor_libro_has_genero_libro_has_idioma_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='Fk_Id_Usuario',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='Fk_Id_Pais',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Idioma',
        ),
        migrations.RemoveField(
            model_name='libro_has_autor',
            name='Fk_Id_Autor',
        ),
        migrations.RemoveField(
            model_name='libro_has_autor',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='libro_has_genero',
            name='Fk_Id_Genero',
        ),
        migrations.RemoveField(
            model_name='libro_has_genero',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='libro_has_idioma',
            name='Fk_Id_Idioma',
        ),
        migrations.RemoveField(
            model_name='libro_has_idioma',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='Fk_Id_Usuario',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Libro_has_Autor',
        ),
        migrations.DeleteModel(
            name='Libro_has_Genero',
        ),
        migrations.DeleteModel(
            name='Libro_has_Idioma',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
