# Generated by Django 3.2.4 on 2023-09-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id_Libro', models.AutoField(db_column='Id_Libro', primary_key=True, serialize=False)),
                ('Fecha_Publicacion', models.DateField(db_column='Fecha_Registro')),
                ('Titulo', models.TextField(db_column='Titulo', max_length=250)),
                ('Sinopsis', models.CharField(db_column='Sinopsis', max_length=300)),
                ('Fk_Id_Autor', models.ForeignKey(db_column='fk_id_Autor', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Editorial', models.ForeignKey(db_column='fk_id_Editorial', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.editorial')),
                ('Fk_Id_Genero', models.ForeignKey(db_column='fk_id_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('Fk_Id_Idioma', models.ForeignKey(db_column='fk_id_Idioma', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
    ]
