# Generated by Django 3.2.4 on 2024-01-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20240108_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Id_Autor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellido_P', models.CharField(max_length=20)),
                ('Apellido_M', models.CharField(max_length=20)),
                ('Biografia', models.TextField()),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='images/autores/')),
            ],
            options={
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('Id_Editorial', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Editorial', models.TextField()),
                ('Sitio_Web', models.URLField()),
            ],
            options={
                'db_table': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('Id_Idioma', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id_Libro', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Registro', models.DateField()),
                ('Titulo', models.TextField()),
                ('Sinopsis', models.CharField(max_length=300)),
                ('en_biblioteca', models.BooleanField(default=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='images/libros/')),
                ('Archivo', models.FileField(blank=True, null=True, upload_to='files/libros/')),
                ('Fk_Id_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editorial')),
                ('Fk_Id_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('Id_Pais', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('Id_Resena', models.AutoField(primary_key=True, serialize=False)),
                ('Calificacion', models.IntegerField()),
                ('Comentario', models.CharField(max_length=150)),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Idioma',
            fields=[
                ('Id_Libro_has_Idioma', models.AutoField(primary_key=True, serialize=False)),
                ('Fk_Id_Idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Idioma',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Genero',
            fields=[
                ('Id_Libro_has_Genero', models.AutoField(primary_key=True, serialize=False)),
                ('Fk_Id_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Genero',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Autor',
            fields=[
                ('Id_Libro_has_Autor', models.AutoField(primary_key=True, serialize=False)),
                ('Fk_Id_Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Autor',
            },
        ),
        migrations.AddField(
            model_name='editorial',
            name='Fk_Id_Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pais'),
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('Id_Biblioteca', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fk_Id_Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Biblioteca',
            },
        ),
        migrations.AddField(
            model_name='autor',
            name='Fk_Id_Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pais'),
        ),
    ]
