# Generated by Django 3.2.4 on 2023-09-19 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230919_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Id_Autor', models.AutoField(db_column='Id_Autor', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=25)),
                ('Apellido_P', models.CharField(db_column='Apellido_P', max_length=20)),
                ('Apellido_M', models.CharField(db_column='Apellido_M', max_length=20)),
                ('Biografia', models.CharField(db_column='Biografia', max_length=200)),
                ('Fk_Id_pais', models.ForeignKey(db_column='fk_pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
            ],
            options={
                'db_table': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('Id_Editorial', models.AutoField(db_column='Id_Editorial', primary_key=True, serialize=False)),
                ('Nombre_Editorial', models.TextField(db_column='Nombre_Editorial')),
                ('Sitio_Web', models.URLField(db_column='Sitio_Web')),
                ('Fk_Id_pais', models.ForeignKey(db_column='fk_pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.pais')),
            ],
            options={
                'db_table': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id_Libro', models.AutoField(db_column='Id_Libro', primary_key=True, serialize=False)),
                ('Fecha_Publicacion', models.DateField(db_column='Fecha_Registro')),
                ('Titulo', models.TextField(db_column='Titulo', max_length=250)),
                ('Sinopsis', models.CharField(db_column='Sinopsis', max_length=300)),
                ('Fk_Id_Autor', models.ForeignKey(db_column='fk_id_Autor', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Editorial', models.ForeignKey(db_column='fk_id_Editorial', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.editorial')),
                ('Fk_Id_Genero', models.ForeignKey(db_column='fk_id_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
                ('Fk_Id_Idioma', models.ForeignKey(db_column='fk_id_Idioma', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('Id_Resena', models.AutoField(db_column='Id_Resena', primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(db_column='Calificacion')),
                ('Comentario', models.CharField(db_column='Comentario', max_length=150)),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(db_column='Fk_Id_Usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='Lista_Deseos',
            fields=[
                ('id_Lista_Deseos', models.AutoField(db_column='Id_Lista_Deseos', primary_key=True, serialize=False)),
                ('Fecha_Agregado', models.DateTimeField(db_column='Fecha_Agregado')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(db_column='Fk_Id_Usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Lista_Deseados',
            },
        ),
        migrations.CreateModel(
            name='Bibilioteca',
            fields=[
                ('Id_Biblioteca', models.AutoField(db_column='Id_Biblioteca', primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateTimeField(db_column='Fecha_Inicio')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(db_column='Fk_Id_Usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Biblioteca',
            },
        ),
    ]
