# Generated by Django 3.2.4 on 2023-09-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_autor_bibilioteca_editorial_libro_lista_deseos_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibilioteca',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='bibilioteca',
            name='Fk_Id_Usuario',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='Fk_Id_pais',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Autor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Genero',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Fk_Id_Idioma',
        ),
        migrations.RemoveField(
            model_name='lista_deseos',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='lista_deseos',
            name='Fk_Id_Usuario',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='Fk_Id_Libro',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='Fk_Id_Usuario',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Bibilioteca',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
        migrations.DeleteModel(
            name='Libro',
        ),
        migrations.DeleteModel(
            name='Lista_Deseos',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
