# Generated by Django 3.2.4 on 2023-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230926_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='Descripcion',
            field=models.TextField(db_column='Descripcion', unique=True),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='Descripcion',
            field=models.TextField(db_column='Descripcion', unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.EmailField(db_column='Correo', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre_Usuario',
            field=models.TextField(db_column='Nombre_Usuario', unique=True),
        ),
    ]
