# Generated by Django 3.2.4 on 2023-09-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230926_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Libro_has_Genero',
        ),
    ]
