# Generated by Django 3.2.4 on 2023-09-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_libro_has_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro_has_Genero',
            fields=[
                ('Id_Libro_has_Genero', models.AutoField(db_column='Id_Libro_has_Genero', primary_key=True, serialize=False)),
                ('Fk_Id_Genero', models.ForeignKey(db_column='Fk_Id_Genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Genero',
            },
        ),
    ]
