# Generated by Django 3.2.4 on 2023-10-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_bibilioteca_libro_libro_has_autor_libro_has_genero_libro_has_idioma_lista_deseos_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Apellido_Ma',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Telefono',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Contrasena',
            field=models.TextField(db_column='Contrasena', editable=False),
        ),
    ]
