# Generated by Django 3.2.4 on 2023-10-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_usuario_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Apellido_Ma',
            field=models.CharField(db_column='Apellido_M', default='carol', max_length=20),
            preserve_default=False,
        ),
    ]
