# Generated by Django 3.2.4 on 2023-10-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_usuario_apellido_ma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Apellido_Ma',
        ),
    ]
