# Generated by Django 3.2.4 on 2023-10-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_usuario_apellido_ma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='COOC', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Contrasena',
            field=models.TextField(db_column='Contrasena', editable=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre_Usuario',
            field=models.TextField(db_column='Nombre_Usuario', null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
