# Generated by Django 3.2.4 on 2023-11-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_encuestasatisfaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='Fk_Id_pais',
            new_name='Fk_Id_Pais',
        ),
        migrations.RenameField(
            model_name='editorial',
            old_name='Fk_Id_pais',
            new_name='Fk_Id_Pais',
        ),
    ]
