# Generated by Django 3.2.4 on 2023-11-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_autor_bibilioteca_editorial_libro_libro_has_autor_libro_has_genero_libro_has_idioma_lista_deseos_res'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lista_Deseos',
        ),
    ]
