# Generated by Django 3.2.4 on 2023-11-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20231114_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id_Libro', models.AutoField(db_column='Id_Libro', primary_key=True, serialize=False)),
                ('Fecha_Publicacion', models.DateField(db_column='Fecha_Registro')),
                ('Titulo', models.TextField(db_column='Titulo', max_length=250)),
                ('Sinopsis', models.CharField(db_column='Sinopsis', max_length=300)),
                ('en_biblioteca', models.BooleanField(default=True)),
                ('Fk_Id_Autor', models.ForeignKey(db_column='fk_id_Autor', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Editorial', models.ForeignKey(db_column='fk_id_Editorial', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.editorial')),
                ('Fk_Id_Genero', models.ForeignKey(db_column='fk_id_Genero', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Idioma', models.ForeignKey(db_column='fk_id_Idioma', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
            ],
            options={
                'db_table': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('Id_Resena', models.AutoField(db_column='Id_Resena', primary_key=True, serialize=False)),
                ('Calificacion', models.IntegerField(db_column='Calificacion')),
                ('Comentario', models.CharField(db_column='Comentario', max_length=150)),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(db_column='Fk_Id_Usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Resena',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Idioma',
            fields=[
                ('Id_Libro_has_Idioma', models.AutoField(db_column='Id_Libro_has_Idioma', primary_key=True, serialize=False)),
                ('Fk_Id_Idioma', models.ForeignKey(db_column='Fk_Id_Idioma', on_delete=django.db.models.deletion.CASCADE, to='api.idioma')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Idioma',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Genero',
            fields=[
                ('Id_Libro_has_Genero', models.AutoField(db_column='Id_Libro_has_Genero', primary_key=True, serialize=False)),
                ('Fk_Id_Genero', models.ForeignKey(db_column='Fk_Id_Genero', on_delete=django.db.models.deletion.CASCADE, to='api.genero')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Genero',
            },
        ),
        migrations.CreateModel(
            name='Libro_has_Autor',
            fields=[
                ('Id_Libro_has_Autor', models.AutoField(db_column='Id_Libro_has_Autor', primary_key=True, serialize=False)),
                ('Fk_Id_Autor', models.ForeignKey(db_column='Fk_Id_Autor', on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
            ],
            options={
                'db_table': 'Libro_has_Autor',
            },
        ),
        migrations.CreateModel(
            name='Bibilioteca',
            fields=[
                ('Id_Biblioteca', models.AutoField(db_column='Id_Biblioteca', primary_key=True, serialize=False)),
                ('Fecha_Inicio', models.DateTimeField(db_column='Fecha_Inicio')),
                ('Fk_Id_Libro', models.ForeignKey(db_column='Fk_Id_Libro', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.libro')),
                ('Fk_Id_Usuario', models.ForeignKey(db_column='Fk_Id_Usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Biblioteca',
            },
        ),
    ]
